### ISSUE TITLE
m.image doesn't contain url property

### ISSUE THREAD

**Issue by rrix** [matrix-org/matrix-appservice-slack#14]
I'm not sure if this or slackbridge is running the #DWebSummit bridge, but the m.image messages coming from the bridge aren't up to spec:

```
((thumbnail_url . "https://files.slack.com/files-tmb/T14KGBP17-F1G4EB0MA-cf6a09a2d5/jason_griffey_builders_day_6-7-16_360.jpg") (thumbnail_info (w . 360) (h . 240)) (msgtype . "m.image") (info (w . 750) (size . 47866) (mimetype . "image/jpeg") (h . 500)) (body . "Jason Griffey Builders Day 6-7-16.jpg"))                                                                      
```

[Spec](https://matrix.org/docs/spec/client_server/r0.1.0.html#m-image) says that `url' is required.

**Comment by ara4n** [comment]
@oddvar

**Comment by leonerd** [comment]
Looking at the latest source that implements this, I believe this bug is now fixed. At least, this commit adds the `url` parameter, which postdates this bug.
  https://github.com/matrix-org/matrix-appservice-slack/commit/906c2cc23a812ba96fcb8b46c4953b6deafeed9c

@oddvar - are you happy? Can we mark this bug as closed/fixed?

**Comment by oddvar** [comment]
ah yes, this was fixed.
