### ISSUE TITLE
There's no way to tell what slack channel a room is bridged into

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-slack#35]

**Comment by leonerd** [comment]
Actually currently this is more a bug with the Slack webhook API system. We just work with a URL that's opaque to us. We post into a URL and messages apparently turn up in Slack, but we don't know where that goes. In addition, some messages happen to arrive from Slack. Admittedly in that case we can extract a channel and team name from the event. But until that first message, we won't know.

This sort of thing would be a lot nicer once we're using the RTM API instead of webhooks.

**Comment by Half-Shot** [comment]
We don't do this with webhooks due to its impossible-ness but you can use admin commands or scalar to determine this with the bot API
